import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "yet-another-react-lightbox/styles.css";
import "./globals.css";

const poppins = Poppins({
   subsets: ["latin"],
   weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
   title: "My Portfolio",
   description: "Generated by next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
   return (
      <html lang="en">
         <body className={`${poppins.className} bg-primary`} style={{ height: "5000px" }}>
            {children}
         </body>
      </html>
   );
}
